### ISSUE TITLE
problem with radars_graph.py

### ISSUE THREAD

**Issue by pbarjoueian** [andrebrener/match_data#2]
Hi

I try to run this file with default data but i get this error every time:

`Traceback (most recent call last):
  File "radars_graph.py", line 131, in <module>
    plot_graph(df, global_stats, players)
  File "radars_graph.py", line 92, in plot_graph
    radar.plot(df[pl], bc)
  File "radars_graph.py", line 64, in plot
    sdata = _scale_data(data, self.ranges)
  File "radars_graph.py", line 18, in _scale_data
    assert (y1 <= d <= y2) or (y2 <= d <= y1)
AssertionError`

**Comment by andrebrener** [comment]
Hi - thanks for issuing. 
That error arises when there is a value in a certain dimension that is outside the limits. 
Please check that the values that you try to plot are between the limits established for each dimension. 
This could be confusing when using negative numbers.

**Comment by pbarjoueian** [comment]
Actually I didn’t use any parameter or value. I just run this file ang get this error.
I didn’t change anything.

Thanks for responding.
